version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www/html/superametas'
    database:
        image: 'mysql:5.7'
        restart: always
        ports:
            - '33006:3306'
        environment:
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=smOnboard
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        volumes:
            - 'database_data:/var/lib/mysql'
            - './.docker/mysql:/docker-entrypoint-initdb.d'
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '8080:80'
        environment:
            - PMA_HOST=database
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=secret
            - UPLOAD_LIMIT=50M
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    web:
        image: sail-8.0/app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "80:80"
volumes:
    database_data: null
    sail-mysql:
        driver: local
networks:
    sail:
        driver: bridge
    frontend-network:
        external: true
